version: '3.8'

services:
  api-db:
    container_name: court-booking-db
    image: postgres:14
    env_file: ./.env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER']
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - ${DB_PORT:-5433}:5432
  api-cache:
    image: redis
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - ${REDIS_PORT:-6380}:6379

  redisinsight:
    image: redislabs/redisinsight
    ports:
      - ${REDIS_INSIGHT_PORT:-6381}:8001
