name: CI

on:
  pull_request:
    branches:
      - dev

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v3

      - run: git branch --track dev origin/dev

      - run: npx nx affected -t lint,test,build --parallel=3
