name: CI

on:
  pull_request:
    branches:
      - dev
      - master

permissions:
  actions: read
  contents: read

jobs:
  code_quality_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: yarn install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v3

      - run: git branch --track dev origin/dev

      - run: npx nx run api:gen-types --no-cloud

      - run: npx nx affected -t lint,test,build --parallel=3 --no-cloud
