name: CI

on:
  pull_request:
    branches:
      - dev
      - master

permissions:
  actions: read
  contents: read

jobs:
  code_quality_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Restore cached yarn dependencies
        uses: actions/cache/restore@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: yarn-dependencies-${{ hashFiles('yarn-lock.yaml') }}

      - run: yarn install --frozen-lockfile

      - name: Cache yarn dependencies
        uses: actions/cache/save@v3
        with:
          path: |
            node_modules
            ~/.cache/Cypress # needed for the Cypress binary
          key: yarn-dependencies-${{ hashFiles('yarn-lock.yaml') }}

      - uses: nrwl/nx-set-shas@v3
      - run: git branch --track dev origin/dev
      - run: npx nx run api:gen-types

      - run: npx nx affected -t lint,test,build --parallel=3
